### ISSUE TITLE
Elastic Docker example should only contain Elastic examples

### ISSUE THREAD

**Issue by KilimAnnejaro** [geopython/pygeoapi-examples#6]
From <https://github.com/geopython/pygeoapi-examples/issues/8>:

**Description**
In the elastic docker example, [pygeoapi is configured to serve 4 datasets](https://github.com/geopython/pygeoapi-examples/blob/main/docker/elastic/pygeoapi/docker.config.yml#L88), but only 1 of them is actually [using elastic as a backend provider](https://github.com/geopython/pygeoapi-examples/blob/main/docker/elastic/pygeoapi/docker.config.yml#L124).

**Steps to Reproduce**
Start the docker-compose file and navigate to the collections page. You will see 4 datasets there.

<img width="1440" alt="272300502-5dfdf86b-2b7a-47b4-9d9f-402822c85723" src="https://github.com/geopython/pygeoapi-examples/assets/16429283/54f18714-3635-4a88-a909-4fd12fa410b6">

These datasets use different providers: CSV, GeoJSON, SQLiteGPKG. Only one of them uses elastic.

**Expected behavior**

In this example, we should publish only the dataset that is served using the elastic provider:

<img width="1440" alt="272300155-98889862-26a3-4421-9760-9d7c3a6cd263" src="https://github.com/geopython/pygeoapi-examples/assets/16429283/7b05f0d4-5d75-4a32-b584-ef6282030bb4">

In order to achieve this, you can edit the [pygeoapi configuration file](https://github.com/geopython/pygeoapi-examples/blob/main/docker/elastic/pygeoapi/docker.config.yml) to remove all the datasets that are not published using the elastic provider.

**Comment by tomkralidis** [comment]
Closing in lieu of #8 (now transferred here).
